### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in TelnetServer::messageReceived

### ISSUE THREAD

**Issue by nirdroid** [kairosdb/kairosdb#143]
TelnetServer.java, line 74

whenever the telnet get bad/empty message, the following line contains empty array
String[] command = (String[]) message;
the exception raises from following line which tries to get the first element although it doesn't exist
TelnetCommand telnetCommand = m_commands.getCommand(command[0]);

01-21|14:22:34.163 [New I/O worker #1] WARN  [TelnetServer.java:122] - Unknown command: 
01-21|14:22:34.376 [New I/O worker #1] WARN  [JdkLogger.java:80] - EXCEPTION, please implement org.kairosdb.core.telnet.TelnetServer.exceptionCaught() for proper handl
ing.
java.lang.ArrayIndexOutOfBoundsException: 0
        at org.kairosdb.core.telnet.TelnetServer.messageReceived(TelnetServer.java:81) ~[kairosdb-0.9.4-6.jar:0.9.4-6.20140730155353]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88) ~[netty-3.6.5.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.5.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
01-21|14:26:54.098 [Thread-1] INFO  [Main.java:390] - Shutting down

**Comment by brianhks** [comment]
The first element should be the command, in most cases this is 'put'.  It couldn't find one so it throw an error.

**Comment by nirdroid** [comment]
yes, but this error in uncaught, so the server shuts down (look at the last line: INFO [Main.java:390] - Shutting down)
it just needs a simple catch & log

**Comment by brianhks** [comment]
Hmm, I wasn't able to shutdown the server but I added some code to make it a little more defensive.
