### ISSUE TITLE
shows 'java.io.IOException: No such file or directory'

### ISSUE THREAD

**Issue by guofan** [kairosdb/kairosdb#153]
on the same machine, if use ./bin/kairosdb.sh export ***, then query some metric, showed:
Status Code: 500
Status: Internal Server Error
Return Value: {"errors":["No such file or directory"]}
stack trace is:
03-02|20:58:43.802 [qtp1544814583-68] ERROR [MetricsResource.java:475] - Failed to open temp folder ./query_cache/1425300470925/
java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:1.7.0_51]
        at java.io.File.createNewFile(File.java:1006) ~[na:1.7.0_51]
        at java.io.File.createTempFile(File.java:1989) ~[na:1.7.0_51]
        at org.kairosdb.core.http.rest.MetricsResource.get(MetricsResource.java:402) ~[kairosdb-0.9.5-0.1beta.jar:0.9.5-0.1beta.20150126131205]

**Comment by guofan** [comment]
when i used export, kairosdb will clear query_cache directory, so the serving kairosdb cannot find it's query_cache directory

**Comment by FrEaKmAn** [comment]
but if there is not query_cache folder, it should rebuild it... do you run query after or during export?
