### ISSUE TITLE
implement org.kairosdb.core.telnet.TelnetServer.exceptionCaught() for proper handling

### ISSUE THREAD

**Issue by jsabin** [kairosdb/kairosdb#195]
just got this exception.  Seems like one of my clients is disconnecting.. but what is this error?  Seems like a bug? Or maybe the exception isn't clear?

07-09|13:05:51.744 [New I/O worker #21] WARN  [JdkLogger.java:80] - EXCEPTION, please implement org.kairosdb.core.telnet.TelnetServer.exceptionCaught() for proper handling.

java.io.IOException: Connection reset by peer

at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.7.0_80]

at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.7.0_80]

at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.7.0_80]

at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.7.0_80]

at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384) ~[na:1.7.0_80]

at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64) ~[netty-3.6.5.Final.jar:na]

at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107) ~[netty-3.6.5.Final.jar:na]

at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[netty-3.6.5.Final.jar:na]

at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88) ~[netty-3.6.5.Final.jar:na]

at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.5.Final.jar:na]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]

at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]

**Comment by jsabin** [comment]
See this for an explanation:

https://groups.google.com/forum/#!topic/unfiltered-scala/DxNhwrYh3Y8

**Comment by jsabin** [comment]
Brian already added the exceptionCaught() method. This has been fixed.
