### ISSUE TITLE
Add EventBus for plugins to get access to incoming metrics

### ISSUE THREAD

**Issue by brianhks** [kairosdb/kairosdb#211]
Guava has an event bus class that makes adding listeners very clean.

**Comment by lcoulet** [comment]
That sounds great, really! And I'm looking forward for this feature.

But please could you NOT drop the existing plugin interfaces?

**Comment by spaced** [comment]
already happen. tried to use plugin with 1.2.1..tried to change to
```
	private final Publisher<DataPointEvent> m_publisher;
```
but fails with
08-12|22:53:40.611 [main] INFO  [CarbonServerModule.java:31] - Configuring module CarbonServerModule
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
```
1) Explicit bindings are required and org.kairosdb.eventbus.Publisher<org.kairosdb.events.DataPointEvent> is not explicitly bound.
  while locating org.kairosdb.eventbus.Publisher<org.kairosdb.events.DataPointEvent>
    for the 1st parameter of org.kairosdb.plugin.carbon.CarbonPickleServer.<init>(CarbonPickleServer.java:66)
  at org.kairosdb.plugin.carbon.CarbonServerModule.configure(CarbonServerModule.java:54)

2) Explicit bindings are required and org.kairosdb.eventbus.Publisher<org.kairosdb.events.DataPointEvent> is not explicitly bound.
  while locating org.kairosdb.eventbus.Publisher<org.kairosdb.events.DataPointEvent>
    for the 1st parameter of org.kairosdb.plugin.carbon.CarbonTextServer.<init>(CarbonTextServer.java:65)
  at org.kairosdb.plugin.carbon.CarbonServerModule.configure(CarbonServerModule.java:53)

2 errors
```
plugin constructor:
```
	@Inject
	public CarbonTextServer(Publisher<DataPointEvent> publisher,
			TagParser tagParser, @Named("kairosdb.carbon.text.port") int port,
			@Named("kairosdb.carbon.text.address") String address)
	{
		m_publisher = publisher;
```
any advise?
