### ISSUE TITLE
TimeOutException

### ISSUE THREAD

**Issue by weirdy** [kairosdb/kairosdb#235]
Hi,

We're using 2 nodes Cassandra cluster (under Kairosdb) with no replication. Each node and kairos are placed on different virtual machines. 
We're trying to insert and read high volume data (about 20k points / sec), and sometimes we've started facing the following errors:

> [pool-2-thread-5] WARN  [HConnectionManager.java:302] - Could not fullfill request on this host CassandraClient<192.168.2.126:9160-28>
[pool-2-thread-5] WARN  [HConnectionManager.java:303] - Exception: 
me.prettyprint.hector.api.exceptions.HTimedOutException: TimedOutException(acknowledged_by:0)
	at me.prettyprint.cassandra.service.ExceptionsTranslatorImpl.translate(ExceptionsTranslatorImpl.java:42) ~[hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:260) ~[hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.model.ExecutingKeyspace.doExecuteOperation(ExecutingKeyspace.java:113) [hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.model.MutatorImpl.execute(MutatorImpl.java:243) [hector-core-1.1-4.jar:na]
	at org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob.run(WriteBuffer.java:372) [kairosdb-1.0.0-1.jar:1.0.0-1.20150604225857]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: org.apache.cassandra.thrift.TimedOutException: null
	at org.apache.cassandra.thrift.Cassandra$batch_mutate_result.read(Cassandra.java:20849) ~[cassandra-thrift-1.2.5.jar:1.2.5]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78) ~[libthrift-0.7.0.jar:0.7.0]
	at org.apache.cassandra.thrift.Cassandra$Client.recv_batch_mutate(Cassandra.java:964) ~[cassandra-thrift-1.2.5.jar:1.2.5]
	at org.apache.cassandra.thrift.Cassandra$Client.batch_mutate(Cassandra.java:950) ~[cassandra-thrift-1.2.5.jar:1.2.5]
	at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:246) ~[hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:243) ~[hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.service.Operation.executeAndSetResult(Operation.java:104) ~[hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:253) ~[hector-core-1.1-4.jar:na]
	... 8 common frames omitted

Does it mean that we've lost the data or Hector somehow handle it and repeat such requests ?
Could you provide some recommendations what to do in this case? probably we need to decrease the batch size or to adjust some config values ?

**Comment by weirdy** [comment]
Curiously, I've stopped to send points in Kairosdb 1 hour ago, but it is still showing these timeout messages. Nothing is sending to kairosdb now. Guys, any ideas how to define what is happening ?

**Comment by brianhks** [comment]
When you these tests you need to watch your cassandra load levels and cpu.  My guess is that you maxed them out.  When an error occurs sending data to Cassandra, Kairos will retry until it is sent and at the same time throttle the data going to Cassandra.

This error looks to me like Cassandra is overwhelmed.  If you want to send that much data you should have a larger cluster.

**Comment by weirdy** [comment]
thanks, brianhks.

1) What is the threshold until an operation is considered as timeout operation in Kairosdb (1 second, 2 seconds, 3 seconds) ? Is it possible to influence on this value via config file ?

2) Am I right that if timeouts happen, Kairosdb will retry to send this data to Cassandra again and again until it succeded ? If it is correct, can this retry count be configurable somewhere?

3) Sometimes these timeout messages are logged as WARN message, sometimes - as ERROR message. What is the difference between two of them in this case ?

I'm experiencing the same issue when trying to send low intensive data and it usually happens after 2-3 hours has elapsed. During this time, I cannot find any signs of big load of cpu, memory or anything else on Cassandra clusters.

**Comment by weirdy** [comment]
I've turned on all debug logs in Kairosdb. Below is the slice of this log. I've stopped sending points more than hour ago, but sometimes timeout messages appear anyway. 

Am I right that the message "Retry service fired... nothing to do" indicates that Kairosdb tries to connect to Cassandra each time even there is nothing to send ? Can these connections hypothetically cause such timeout errors ?

>11-13|15:23:34.500 [Hector.me.prettyprint.cassandra.connection.CassandraHostRetryService-1] DEBUG [CassandraHostRetryService.java:123] - Retry service fired... nothing to do.
11-13|15:23:44.515 [Hector.me.prettyprint.cassandra.connection.CassandraHostRetryService-1] DEBUG [CassandraHostRetryService.java:123] - Retry service fired... nothing to do.
11-13|15:23:53.797 [QuartzScheduler_QuartzSchedulerThread] DEBUG [QuartzSchedulerThread.java:268] - batch acquisition of 1 triggers
11-13|15:23:54.530 [Hector.me.prettyprint.cassandra.connection.CassandraHostRetryService-1] DEBUG [CassandraHostRetryService.java:123] - Retry service fired... nothing to do.
11-13|15:24:00.006 [QuartzScheduler_Worker-2] DEBUG [JobRunShell.java:212] - Calling execute on job DEFAULT.org.kairosdb.core.jobs.CacheFileCleaner
11-13|15:24:00.006 [QuartzScheduler_QuartzSchedulerThread] DEBUG [QuartzSchedulerThread.java:268] - batch acquisition of 1 triggers
11-13|15:24:00.006 [QuartzScheduler_Worker-2] DEBUG [CacheFileCleaner.java:49] - Executing job...
11-13|15:24:00.006 [QuartzScheduler_Worker-3] DEBUG [JobRunShell.java:212] - Calling execute on job DEFAULT.org.kairosdb.core.reporting.MetricReporterService
11-13|15:24:00.006 [QuartzScheduler_QuartzSchedulerThread] DEBUG [QuartzSchedulerThread.java:268] - batch acquisition of 0 triggers
11-13|15:24:00.006 [QuartzScheduler_Worker-3] DEBUG [MetricReporterService.java:93] - Reporting metrics
11-13|15:24:00.021 [QuartzScheduler_Worker-1] DEBUG [KairosDatastore.java:164] - Executing job...
11-13|15:24:00.021 [QuartzScheduler_Worker-1] DEBUG [KairosDatastore.java:166] - Deleting cache files in C:\Users\ADMINI~1\AppData\Local\Temp\kairos_cache\1447417320011
11-13|15:24:00.021 [QuartzScheduler_Worker-1] DEBUG [CacheFileCleaner.java:51] - Job Completed
11-13|15:24:00.021 [pool-2-thread-5] TRACE [HThriftClient.java:209] - Transport open status true for client CassandraClient<192.168.2.126:9160-57>
11-13|15:24:02.049 [pool-2-thread-5] DEBUG [HThriftClient.java:126] - Closing client CassandraClient<192.168.2.126:9160-57>
11-13|15:24:02.049 [pool-2-thread-5] TRACE [HThriftClient.java:209] - Transport open status true for client CassandraClient<192.168.2.126:9160-57>
11-13|15:24:02.049 [pool-2-thread-5] WARN  [HConnectionManager.java:302] - Could not fullfill request on this host CassandraClient<192.168.2.126:9160-57>
11-13|15:24:02.049 [pool-2-thread-5] WARN  [HConnectionManager.java:303] - Exception: 
me.prettyprint.hector.api.exceptions.HTimedOutException: TimedOutException(acknowledged_by:0)
	at me.prettyprint.cassandra.service.ExceptionsTranslatorImpl.translate(ExceptionsTranslatorImpl.java:42) ~[hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:260) ~[hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.model.ExecutingKeyspace.doExecuteOperation(ExecutingKeyspace.java:113) [hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.model.MutatorImpl.execute(MutatorImpl.java:243) [hector-core-1.1-4.jar:na]
	at org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob.run(WriteBuffer.java:372) [kairosdb-1.0.0-1.jar:1.0.0-1.20150604225857]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: org.apache.cassandra.thrift.TimedOutException: null
	at org.apache.cassandra.thrift.Cassandra$batch_mutate_result.read(Cassandra.java:20849) ~[cassandra-thrift-1.2.5.jar:1.2.5]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78) ~[libthrift-0.7.0.jar:0.7.0]
	at org.apache.cassandra.thrift.Cassandra$Client.recv_batch_mutate(Cassandra.java:964) ~[cassandra-thrift-1.2.5.jar:1.2.5]
	at org.apache.cassandra.thrift.Cassandra$Client.batch_mutate(Cassandra.java:950) ~[cassandra-thrift-1.2.5.jar:1.2.5]
	at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:246) ~[hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:243) ~[hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.service.Operation.executeAndSetResult(Operation.java:104) ~[hector-core-1.1-4.jar:na]
	at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:253) ~[hector-core-1.1-4.jar:na]
	... 8 common frames omitted
11-13|15:24:02.049 [pool-2-thread-5] TRACE [HThriftClient.java:209] - Transport open status false for client CassandraClient<192.168.2.126:9160-57>
11-13|15:24:02.049 [pool-2-thread-5] TRACE [HThriftClient.java:209] - Transport open status false for client CassandraClient<192.168.2.126:9160-109>

**Comment by noorul** [comment]
I am also seeing this and there is no stress on cassandra node

`02-18|08:57:40.214 [qtp2031469076-71] DEBUG [HttpParser.java:281] - filled 0/0
02-18|08:57:40.221 [pool-5-thread-6] DEBUG [HThriftClient.java:126] - Closing client CassandraClient<10.12.22.13:9160-111>
02-18|08:57:40.221 [pool-5-thread-6] WARN  [HConnectionManager.java:302] - Could not fullfill request on this host CassandraClient<10.12.22.13:9160-111>
02-18|08:57:40.221 [pool-5-thread-6] WARN  [HConnectionManager.java:303] - Exception:
me.prettyprint.hector.api.exceptions.HTimedOutException: TimedOutException(acknowledged_by:1)
        at me.prettyprint.cassandra.service.ExceptionsTranslatorImpl.translate(ExceptionsTranslatorImpl.java:42) ~[hector-core-1.1-4.jar:na]
        at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:260) ~[hector-core-1.1-4.jar:na]
        at me.prettyprint.cassandra.model.ExecutingKeyspace.doExecuteOperation(ExecutingKeyspace.java:113) [hector-core-1.1-4.jar:na]
        at me.prettyprint.cassandra.model.MutatorImpl.execute(MutatorImpl.java:243) [hector-core-1.1-4.jar:na]
        at org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob.run(WriteBuffer.java:372) [kairosdb-1.1.1-2.jar:1.1.1-2.20160216153340]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
Caused by: org.apache.cassandra.thrift.TimedOutException: null
        at org.apache.cassandra.thrift.Cassandra$batch_mutate_result.read(Cassandra.java:20849) ~[cassandra-thrift-1.2.5.jar:1.2.5]
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78) ~[libthrift-0.7.0.jar:0.7.0]
        at org.apache.cassandra.thrift.Cassandra$Client.recv_batch_mutate(Cassandra.java:964) ~[cassandra-thrift-1.2.5.jar:1.2.5]
        at org.apache.cassandra.thrift.Cassandra$Client.batch_mutate(Cassandra.java:950) ~[cassandra-thrift-1.2.5.jar:1.2.5]
        at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:246) ~[hector-core-1.1-4.jar:na]
        at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:243) ~[hector-core-1.1-4.jar:na]
        at me.prettyprint.cassandra.service.Operation.executeAndSetResult(Operation.java:104) ~[hector-core-1.1-4.jar:na]
        at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:253) ~[hector-core-1.1-4.jar:na]
        ... 8 common frames omitted
02-18|08:57:40.222 [pool-5-thread-6] INFO  [HThriftClientFactoryImpl.java:31] - SSL enabled for client<->server communications.
02-18|08:57:40.222 [pool-5-thread-6] DEBUG [HThriftClientFactoryImpl.java:33] - Properties:
02-18|08:57:40.222 [pool-5-thread-6] DEBUG [HThriftClientFactoryImpl.java:34] -   ssl.truststore = /opt/kairosdb/conf/.truststore
02-18|08:57:40.222 [pool-5-thread-6] DEBUG [HThriftClientFactoryImpl.java:35] -   ssl.protocol = null
02-18|08:57:40.222 [pool-5-thread-6] DEBUG [HThriftClientFactoryImpl.java:36] -   ssl.store.type = null
02-18|08:57:40.222 [pool-5-thread-6] DEBUG [HThriftClientFactoryImpl.java:37] -   ssl.cipher.suites = null
02-18|08:57:40.222 [pool-5-thread-6] DEBUG [HThriftClientFactoryImpl.java:38] - Creation of new client for host: 10.12.22.13
02-18|08:57:40.222 [pool-5-thread-6] DEBUG [HThriftClient.java:152] - Creating a new thrift connection to 10.12.22.13(10.12.22.13):9160
02-18|08:57:40.223 [qtp2031469076-115] DEBUG [HttpParser.java:281] - filled 4029/4029`

**Comment by MartinNowak** [comment]
You could increase `kairosdb.datastore.cassandra.hector.cassandraThriftSocketTimeout` to let KairosDB/Hector wait longer for responses.

**Comment by noorul** [comment]
That is set to 0 which means no timeout.

**Comment by MartinNowak** [comment]
> That is set to 0 which means no timeout.

Well that apparently doesn't work.
Hector is ignoring a timeout of 0 when applying the config.
https://github.com/hector-client/hector/blob/a302e68ca8d91b45d332e8c9afd7d98030b54de1/core/src/main/java/me/prettyprint/cassandra/service/CassandraHostConfigurator.java#L94
Seems you could set a 0 timeout via ENV variable https://github.com/hector-client/hector/blob/a302e68ca8d91b45d332e8c9afd7d98030b54de1/core/src/main/java/me/prettyprint/cassandra/connection/client/HThriftClient.java#L221, or just set a very high value in the kairosdb config.

**Comment by noorul** [comment]
But it is initialized to zero

https://github.com/hector-client/hector/blob/master/core/src/main/java/me/prettyprint/cassandra/service/CassandraHost.java#L70

**Comment by MartinNowak** [comment]
Mmh, the default configs set it to 10s though.
https://github.com/kairosdb/kairosdb/blob/1261ee8/src/main/resources/kairosdb.properties#L136
