### ISSUE TITLE
graphite/carbon missing??

### ISSUE THREAD

**Issue by DanoOM** [kairosdb/kairosdb#333]
Using: kairosdb-1.1.2-1.tar.gz

I added this to the properties file:

kairosdb.service.carbon=org.kairosdb.core.carbon.CarbonServerModule

but upon startup we get:
10-05|17:54:45.186 [main] ERROR [Main.java:212] - Unable to load service kairosdb.service.carbon
java.lang.ClassNotFoundException: org.kairosdb.core.carbon.CarbonServerModule
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.kairosdb.core.Main.<init>(Main.java:178)
	at org.kairosdb.core.Main.main(Main.java:263)

**Comment by DanoOM** [comment]
From what I can tell, we actually need to grab/build: https://github.com/kairosdb/kairos-carbon

Can we get the docs updated to indicate this? as there is no indication this is required.
https://kairosdb.github.io/docs/build/html/Graphite.html

**Comment by brianhks** [comment]
Sorry for the doc failure.  We did move it out to be it's own plugin.  I'll keep this open until I get the docs updated.
