### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by sokratisg** [kairosdb/kairosdb#340]
We're trying to setup an Apache Storm Bolt for writing to KairosDB and right right now it is working fine based on kairosdb.http.ingest_count. We're pushing data using https://github.com/kairosdb/kairosdb-client which seems to work quite okay unless some exceptions from time to time.

```
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_102]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_102]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95) ~[stormjar.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60) ~[stormjar.jar:?]
        at com.google.gson.Gson.toJson(Gson.java:593) ~[stormjar.jar:?]
        at com.google.gson.Gson.toJson(Gson.java:572) ~[stormjar.jar:?]
        at com.google.gson.Gson.toJson(Gson.java:527) ~[stormjar.jar:?]
        at com.google.gson.Gson.toJson(Gson.java:507) ~[stormjar.jar:?]
        at org.kairosdb.client.builder.MetricBuilder.build(MetricBuilder.java:109) ~[stormjar.jar:?]
        at org.kairosdb.client.AbstractClient.pushMetrics(AbstractClient.java:94) ~[stormjar.jar:?]
        at org.somepackage.KairosdbWriterBolt.execute(KairosdbWriterBolt.java:127) [stormjar.jar:?]
        at org.apache.storm.daemon.executor$fn__8058$tuple_action_fn__8060.invoke(executor.clj:731) [storm-core-1.0.2.jar:1.0.2]
        at org.apache.storm.daemon.executor$mk_task_receiver$fn__7979.invoke(executor.clj:464) [storm-core-1.0.2.jar:1.0.2]
        at org.apache.storm.disruptor$clojure_handler$reify__7492.onEvent(disruptor.clj:40) [storm-core-1.0.2.jar:1.0.2]
        at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:451) [storm-core-1.0.2.jar:1.0.2]
        at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:430) [storm-core-1.0.2.jar:1.0.2]
        at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:73) [storm-core-1.0.2.jar:1.0.2]
        at org.apache.storm.daemon.executor$fn__8058$fn__8071$fn__8124.invoke(executor.clj:850) [storm-core-1.0.2.jar:1.0.2]
        at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:484) [storm-core-1.0.2.jar:1.0.2]
        at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

Only relevant issue I could find is https://github.com/kairosdb/kairosdb/issues/133 which is closed.

Any idea what may be causing these error messages?
Are these coming from the driver or KairosDB http listener?
Any help or suggestions?

Using:
- [KairosDB-Client 2.1.1](https://mvnrepository.com/artifact/org.kairosdb/client/2.1.1)
- KairosDB 1.1.2-1 (installed from Debian package)

**Comment by sokratisg** [comment]
Problem has gone away after switching to the Telnet API push method (putm). I presume issue may had to do with the Java client rather than KairosDB listener.

**Comment by brianhks** [comment]
Looks like a race condition in the client that is not being handled.

**Comment by jsabin** [comment]
I will see if I can reproduce the problem.

**Comment by jsabin** [comment]
Any chance you are using the same instance of MetricBuilder in multiple threads?

**Comment by jsabin** [comment]
I was able to reproduce this exception when multiple threads are using the same MetricBuilder, but the code works fine when each thread has its own instance of MetricBuilder. The Telnet client uses MetricBuilder differently and may appear to work, but MetricBuilder is not thread safe so you will most likely have problems reusing a MetricBuilder. In fact, you should create a new MetricBuilder after each time you call client.pushMetrics().

I realize that the documentation does not indicate that MetricBuilder is not thread safe and probably should.
