### ISSUE TITLE
ttl set to 630720000 (20 years) causes WriteBuffer.java error looping

### ISSUE THREAD

**Issue by jgbruosk** [kairosdb/kairosdb#349]
On a new install of KairosDB 1.1.3 and Cassandra 3.9, I posted the following data to /api/v1/datapoints:
[{
    "name": "sample.data.string",
    "timestamp": 1484164768,
    "type": "string",
    "value": "aNewStringValue",
    "tags":{"test":"test"},
    "ttl":630720000
}] 

A 204 is received, but the data is never stored.  The KairosDB log shows the following errors:

01-12|07:14:52.253 [WriteBuffer-row_key_index-3] ERROR [WriteBuffer.java:332] - Error sending data to Cassandra (row_key_index)
me.prettyprint.hector.api.exceptions.HInvalidRequestException: InvalidRequestException(why:ttl is too large. requested (632534400) maximum (630720000))
	at me.prettyprint.cassandra.service.ExceptionsTranslatorImpl.translate(ExceptionsTranslatorImpl.java:52)
	at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:260)
	at me.prettyprint.cassandra.model.ExecutingKeyspace.doExecuteOperation(ExecutingKeyspace.java:113)
	at me.prettyprint.cassandra.model.MutatorImpl.execute(MutatorImpl.java:243)
	at org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob.run(WriteBuffer.java:325)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
Caused by: org.apache.cassandra.thrift.InvalidRequestException: null
	at org.apache.cassandra.thrift.Cassandra$batch_mutate_result.read(Cassandra.java:20833)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_batch_mutate(Cassandra.java:964)
	at org.apache.cassandra.thrift.Cassandra$Client.batch_mutate(Cassandra.java:950)
	at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:246)
	at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:243)
	at me.prettyprint.cassandra.service.Operation.executeAndSetResult(Operation.java:104)
	at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:253)
	... 6 common frames omitted
01-12|07:14:52.254 [WriteBuffer-row_key_index-3] ERROR [WriteBuffer.java:336] - Reducing write buffer size to 375000.  You need to increase your cassandra capacity or change the kairosdb.datastore.cassandra.write_buffer_max_size property.
01-12|07:14:52.758 [WriteBuffer-row_key_index-3] ERROR [WriteBuffer.java:363] - Error resending data
01-12|07:14:53.260 [WriteBuffer-row_key_index-3] ERROR [WriteBuffer.java:363] - Error resending data

The "Error resending data" message continuously repeats in the log until KairosDB is shutdown.

If I restart KairosDB and change the ttl value to 628473600 (20 years minus 1 day), the request works without error.

**Comment by brianhks** [comment]
Cassandra has set the limit for ttl to 20 years.  Still at some point Kairos should stop trying to send it.  Probably should try the batch a set number of times and then give up.  Ideally it would be nice to get all the data in except the bad one, harder to do.

**Comment by brianhks** [comment]
In this case kairos should check the ttl at the gate and fail the post to the client.

**Comment by jgbruosk** [comment]
The POST used the correct maximum value for ttl (630720000).  Based upon the error message, KairosDB seems to have changed it to 632534400 (InvalidRequestException(why:ttl is too large. requested (632534400) maximum (630720000)).

**Comment by brianhks** [comment]
I see.  When Kairos inserts a value into a row that has a TTL, we also have to insert the row key into an index.  The row key must expire after the data point.  Row keys are inserted into 3 week windows so the row key may expire up to 3 weeks after the data depending on where the data lands in the 3 week window.

I'm guessing this error was from inserting the row key.

**Comment by jgbruosk** [comment]
Thank you for the explanation; now the error makes sense: 01-12|07:14:52.253 [WriteBuffer-row_key_index-3] ERROR [WriteBuffer.java:332] - Error sending data to Cassandra (row_key_index)

It would probably be sufficient to document that the max ttl for KairosDB is 3 weeks less than the max for cassandra for now, and possibly put some limit on the batch retry so it doesn't get stuck on a bad ttl value.

**Comment by carysyd** [comment]
I'm seeing the same issue in our cluster. Looks like once KairosDB gets into this state, it goes into infinite loop and eventually use up all the resources.

Is there a fix for this issue?

**Comment by brianhks** [comment]
Other than don't do it, no.  I'll make sure the next release has a fix for this so it wont freak out.

**Comment by carysyd** [comment]
Hi, @brianhks. Does the new "1.2 Beta 3 Release" still have this issue. Looking forward to trying it out.

**Comment by brianhks** [comment]
I just tested this with 1.2 and I didn't get the same error but the data wasn't inserted.  I ran the following in cqlsh
`cqlsh:test> create table test_ttl (key text, column1 text, value text, primary key (key, column1));`
`cqlsh:test> insert into test_ttl (key, column1, value) values ('mykey', 'mycol', 'myval') using ttl 630720000;`
`cqlsh:test> select * from test_ttl;`
Last line returned nothing.  Seems to be a bug in C*

**Comment by milpol** [comment]
Hi,
Feature bug I would say.
By default C* writes row using current timestamp (in epoch seconds) and indeed the maximum available TTL is 20 years (https://github.com/PaytmLabs/cassandra/blob/master/src/java/org/apache/cassandra/db/ExpiringCell.java).
The problem is that C* uses int to resolve time in epoch seconds, which (by signed MAX_INT) ends at:  January 19, 2038 3:14:07AM. So effectively maximum available TTL is: 
MAX_INT - CURRENT_EPOCH which is _about_ 20 years.

**Comment by chetanadixit17** [comment]
If some one is using 630720000 as ttl then on and after time January 19, 2018 3:14:07AM the inserts shows successful but data will be deleted silently  and permanently from the system in background.  Its a Cassandra bug , https://issues.apache.org/jira/browse/CASSANDRA-14092 , and patch is also available now for this blocker issue.

**Comment by brianhks** [comment]
Thank you for finding that.
