### ISSUE TITLE
Datastore writing errors after moving from KairosDB 1.1.0 to 1.1.3

### ISSUE THREAD

**Issue by rdzimmer** [kairosdb/kairosdb#354]
I am using Cassandra 3.9.  With KairosDB 1.1.0 I have been ingesting ~1 mill metrics per minute sustained, 3 million peak (after restarts when data has queued up).  I have uplifted to KairosDB 1.1.3, but have been having errors posting to Cassandra with it.  I can see the KairosDB heap begin to fill up and thrash.  Some data gets through initially, but eventually it locks up.  1.1.3 is working okay at lower scale,  200,000/minute is fine.  

After some investigation I tried changing my kairosdb.datastore.cassandra.write_buffer_max_size from the default 500,000, eventually all the way down to 1,000.  With this change I am running 1.1.3 at the same scale as I had before with 1.1.0, but I'm getting different errors now (see below).  Looking at the CPU, around once a minute everything pauses for a few seconds, then picks back up again.  My workload is constant, and I didn't see drops in utilization with 1.1.0.  

The main issue seems to be after restarts when backlog data is coming in and the systems are trying to catch up (when it is trying to run at ~3million/minute).  Cassandra is very busy after restarts, but it was just as busy with 1.1.0 and KairosDB was able to handle it being busy then.  I'm wondering if this is related to the fix for issue 346, https://github.com/kairosdb/kairosdb/issues/346.  I never saw data loss before, but will double check this again.  

**Log from KairosDB 1.1.3 with default write_buffer_max_size 500,000:**

01-19|08:41:09.949 [WriteBuffer-row_key_index-3] ERROR [HConnectionManager.java:418] - MARK HOST AS DOWN TRIGGERED for host localhost(127.0.0.1):9160
01-19|08:41:09.949 [WriteBuffer-row_key_index-3] ERROR [HConnectionManager.java:422] - Pool state on shutdown: <ConcurrentCassandraClientPoolByHost>:{localhost(127.0.0.1):9160}; IsActive?: true; Active: 1; Blocked: 0; Idle: 15; NumBeforeExhausted: 49
01-19|08:41:09.949 [WriteBuffer-row_key_index-3] INFO  [ConcurrentHClientPool.java:189] - Shutdown triggered on <ConcurrentCassandraClientPoolByHost>:{localhost(127.0.0.1):9160}
01-19|08:41:09.950 [WriteBuffer-row_key_index-3] INFO  [ConcurrentHClientPool.java:197] - Shutdown complete on <ConcurrentCassandraClientPoolByHost>:{localhost(127.0.0.1):9160}
01-19|08:41:09.950 [WriteBuffer-row_key_index-3] INFO  [CassandraHostRetryService.java:68] - Host detected as down was added to retry queue: localhost(127.0.0.1):9160
01-19|08:41:09.950 [WriteBuffer-row_key_index-3] WARN  [HConnectionManager.java:302] - Could not fullfill request on this host CassandraClient<localhost:9160-14357>
01-19|08:41:09.950 [WriteBuffer-row_key_index-3] WARN  [HConnectionManager.java:303] - Exception:
me.prettyprint.hector.api.exceptions.HectorTransportException: org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe
        at me.prettyprint.cassandra.service.ExceptionsTranslatorImpl.translate(ExceptionsTranslatorImpl.java:39)
        at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:260)
        at me.prettyprint.cassandra.model.ExecutingKeyspace.doExecuteOperation(ExecutingKeyspace.java:113)
        at me.prettyprint.cassandra.model.MutatorImpl.execute(MutatorImpl.java:243)
        at org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob.run(WriteBuffer.java:358)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:785)
Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe
        at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:147)
        at org.apache.thrift.transport.TFramedTransport.flush(TFramedTransport.java:157)
        at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:65)
        at org.apache.cassandra.thrift.Cassandra$Client.send_batch_mutate(Cassandra.java:958)
        at org.apache.cassandra.thrift.Cassandra$Client.batch_mutate(Cassandra.java:949)
        at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:246)
        at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:243)
        at me.prettyprint.cassandra.service.Operation.executeAndSetResult(Operation.java:104)
        at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:253)
        ... 6 common frames omitted
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:120)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:164)
        at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145)
        ... 14 common frames omitted

**Log from 1.1.3 with write_buffer_max_size 1,000:**

01-20|11:14:01.477 [WriteBuffer Scheduler for string_index] ERROR [CassandraDatastore.java:214] -
org.kairosdb.core.exception.DatastoreException: org.kairosdb.core.exception.DatastoreException: Unable to write to datastore, see Kairos logs for cause.
        at org.kairosdb.datastore.cassandra.CassandraDatastore.putDataPoint(CassandraDatastore.java:360)
        at org.kairosdb.datastore.cassandra.CassandraDatastore.putInternalDataPoint(CassandraDatastore.java:210)
        at org.kairosdb.datastore.cassandra.CassandraDatastore.access$100(CassandraDatastore.java:57)
        at org.kairosdb.datastore.cassandra.CassandraDatastore$1.saveWriteSize(CassandraDatastore.java:200)
        at org.kairosdb.datastore.cassandra.WriteBuffer.submitJob(WriteBuffer.java:214)
        at org.kairosdb.datastore.cassandra.WriteBuffer.run(WriteBuffer.java:256)
        at java.lang.Thread.run(Thread.java:785)
Caused by: org.kairosdb.core.exception.DatastoreException: Unable to write to datastore, see Kairos logs for cause.
        at org.kairosdb.datastore.cassandra.WriteBuffer.waitOnBufferFull(WriteBuffer.java:175)
        at org.kairosdb.datastore.cassandra.WriteBuffer.addData(WriteBuffer.java:115)
        at org.kairosdb.datastore.cassandra.CassandraDatastore.putDataPoint(CassandraDatastore.java:354)
        ... 6 common frames omitted
01-20|11:14:01.479 [WriteBuffer Scheduler for data_points] ERROR [CassandraDatastore.java:214] -
org.kairosdb.core.exception.DatastoreException: org.kairosdb.core.exception.DatastoreException: Unable to write to datastore, see Kairos logs for cause.
        at org.kairosdb.datastore.cassandra.CassandraDatastore.putDataPoint(CassandraDatastore.java:360)
        at org.kairosdb.datastore.cassandra.CassandraDatastore.putInternalDataPoint(CassandraDatastore.java:210)
        at org.kairosdb.datastore.cassandra.CassandraDatastore.access$100(CassandraDatastore.java:57)
        at org.kairosdb.datastore.cassandra.CassandraDatastore$1.saveWriteSize(CassandraDatastore.java:200)
        at org.kairosdb.datastore.cassandra.WriteBuffer.submitJob(WriteBuffer.java:214)
        at org.kairosdb.datastore.cassandra.WriteBuffer.run(WriteBuffer.java:256)
        at java.lang.Thread.run(Thread.java:785)
Caused by: org.kairosdb.core.exception.DatastoreException: Unable to write to datastore, see Kairos logs for cause.
        at org.kairosdb.datastore.cassandra.WriteBuffer.waitOnBufferFull(WriteBuffer.java:175)
        at org.kairosdb.datastore.cassandra.WriteBuffer.addData(WriteBuffer.java:115)
        at org.kairosdb.datastore.cassandra.CassandraDatastore.putDataPoint(CassandraDatastore.java:354)
        ... 6 common frames omitted
01-20|11:15:00.748 [QuartzScheduler_Worker-1] ERROR [MetricReporterService.java:129] - Reporter service error
org.kairosdb.core.exception.DatastoreException: org.kairosdb.core.exception.DatastoreException: java.util.concurrent.RejectedExecutionException: Task org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob@a8a09327 rejected from java.util.concurrent.ThreadPoolExecutor@e648259b[Running, pool size = 4, active threads = 4, queued tasks = 60, completed tasks = 43423]
        at org.kairosdb.datastore.cassandra.CassandraDatastore.putDataPoint(CassandraDatastore.java:360)
        at org.kairosdb.core.datastore.KairosDatastore.putDataPoint(KairosDatastore.java:201)
        at org.kairosdb.core.datastore.KairosDatastore.putDataPoint(KairosDatastore.java:193)
        at org.kairosdb.core.reporting.MetricReporterService.execute(MetricReporterService.java:107)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.kairosdb.core.exception.DatastoreException: java.util.concurrent.RejectedExecutionException: Task org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob@a8a09327 rejected from java.util.concurrent.ThreadPoolExecutor@e648259b[Running, pool size = 4, active threads = 4, queued tasks = 60, completed tasks = 43423]
        at org.kairosdb.datastore.cassandra.WriteBuffer.submitJob(WriteBuffer.java:230)
        at org.kairosdb.datastore.cassandra.WriteBuffer.waitOnBufferFull(WriteBuffer.java:179)
        at org.kairosdb.datastore.cassandra.WriteBuffer.addData(WriteBuffer.java:115)
        at org.kairosdb.datastore.cassandra.CassandraDatastore.putDataPoint(CassandraDatastore.java:354)
        ... 5 common frames omitted
Caused by: java.util.concurrent.RejectedExecutionException: Task org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob@a8a09327 rejected from java.util.concurrent.ThreadPoolExecutor@e648259b[Running, pool size = 4, active threads = 4, queued tasks = 60, completed tasks = 43423]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2058)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:834)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1380)
        at org.kairosdb.datastore.cassandra.WriteBuffer.submitJob(WriteBuffer.java:223)
        ... 8 common frames omitted
01-20|11:15:00.919 [qtp-1744757357-150] ERROR [MetricsResource.java:329] - Failed to add metric.
org.kairosdb.core.exception.DatastoreException: org.kairosdb.core.exception.DatastoreException: Unable to write to datastore, see Kairos logs for cause.
        at org.kairosdb.datastore.cassandra.CassandraDatastore.putDataPoint(CassandraDatastore.java:360)
        at org.kairosdb.core.datastore.KairosDatastore.putDataPoint(KairosDatastore.java:201)
        at org.kairosdb.core.http.rest.json.DataPointsParser.validateAndAddDataPoints(DataPointsParser.java:312)
        at org.kairosdb.core.http.rest.json.DataPointsParser.parse(DataPointsParser.java:93)
        at org.kairosdb.core.http.rest.MetricsResource.add(MetricsResource.java:295)
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)

**Comment by rdzimmer** [comment]
I've settled on a kairosdb.datastore.cassandra.write_buffer_max_size=25000 which is working relatively well for me now with KairosDB 1.1.3.  The pauses are not as extreme as when I go with an even lower buffer size.  However, I'm still worried about the state it can get into with write_buffer_max_size=500000 that I never saw with 1.1.0.  Looking back, I see that with 1.1.0 it was auto reducing my write_buffer_max_size down into the 50,000 to 200,000 range.  Perhaps with 1.1.3 and the new retry logic from issue 346 it was not auto reducing my write_buffer_max_size quickly enough compared to 1.1.0?  
I also wanted to make sure I understand what the write_buffer_max_size changes.  Is it how much data is sent to Cassandra all at once in a batch, or is it simply at what point the job starts to send data over to Cassandra (possibly broken up into smaller thrift chunks)?

**Comment by brianhks** [comment]
I'm afraid that in 1.1.0 you were actually loosing data.   If a buffer failed to send the retry never happened because Hector cleared the buffer.  With 1.1.3 it will now continue to retry the data.

The write_buffer_max_size is how much it could potentially try to send to C*.  The buffer is flushed every second or so controlled by kairosdb.datastore.cassandra.write_delay.  If the buffer is full then you will get the error.

Either way it sounds like you have maxed out your C* cluster, looks like you need to add another Kairos node and more C* nodes.

**Comment by rdzimmer** [comment]
Thanks Brian!  A few follow-up clarifications before closing out since I'm sure others could hit similar issues with the 1.1.3 retry code change.  
Steady state (almost all of the time) we're inserting 1 million metrics / minute.  Our Cassandra CPU is between 30% and 50% utilized during steady state.  Disk util 15~30%.  
The issues are definitely limited to after restarts when we have a backlog of data to send to KairosDB.  Our metric providers posting to KairosDB are faster than KairosDB and Cassandra.  Cassandra can get maxed out during the catch-up.  **However, it seems like a waste to add and pay for more Cassandra just to handle the catch-ups faster since steady state utilization is good.**  Instead, I was wondering what is the proper way to handle these backlog/catch-up situations.  
One option would be to throttle our providers.  However, ideally KairosDB should be able to handle the throttling completely for us since it talks to Cassandra, which is the bottleneck during a catch-up load.  Dropping our write_buffer_max_size to 25,000 has kept KairosDB from getting into trouble after restarts.  I know it should be auto-decreasing the write_buffer size for us, but it must not have been dropping down fast enough from the default 500,000 for us.  And since the data was no longer getting thrown away it then ran into heap trouble.  

My big concern is the heap issues I hit with 1.1.3.  Does KairosDB prevent more data from coming in from producers until the "Unable to write to datastore" issues are cleared up?  Or does it just keep receiving all it can from the producers?

**Comment by rdzimmer** [comment]
I've switched back to kairosdb.datastore.cassandra.write_delay=500,000 in my dev env and I'm running more burst tests to narrow down what is going on with the failures.  I've bumped up my KairosDB heap even more than last week.  I think I take back what I said in the previous post about being concerned about the KairosDB heap.  In the garbage collection I can see KairosDB is only using 3GB out of 16GB after collection.  The garbage collection pauses last 230ms every 2 seconds.  Normally it's every ~5 seconds instead, but it definitely doesn't look like a memory shortage to me.  
The weird thing is Cassandra isn't doing anything despite KairosDB having data and wanting to send to it.  I don't see any Cassandra CPU activity and there are no Cassandra errors messages in the logs.  In fact there is nothing new in the Cassandra logs since KairosDB stopped being able to post.  KairosDB's logs are constantly writing these messages below. 

01-23|13:54:35.772 [WriteBuffer-row_key_index-2] ERROR [HConnectionManager.java:418] - MARK HOST AS DOWN TRIGGERED for host localhost(127.0.0.1):9160
01-23|13:54:35.772 [WriteBuffer-row_key_index-2] ERROR [HConnectionManager.java:422] - Pool state on shutdown: <ConcurrentCassandraClientPoolByHost>:{localhost(127.0.0.1):9160}; IsActive?: true; Active: 1; Blocked: 0; Idle: 15; NumBeforeExhausted: 49
01-23|13:54:35.772 [WriteBuffer-row_key_index-2] INFO  [ConcurrentHClientPool.java:189] - Shutdown triggered on <ConcurrentCassandraClientPoolByHost>:{localhost(127.0.0.1):9160}
01-23|13:54:35.773 [WriteBuffer-row_key_index-2] INFO  [ConcurrentHClientPool.java:197] - Shutdown complete on <ConcurrentCassandraClientPoolByHost>:{localhost(127.0.0.1):9160}
01-23|13:54:35.773 [WriteBuffer-row_key_index-2] INFO  [CassandraHostRetryService.java:68] - Host detected as down was added to retry queue: localhost(127.0.0.1):9160
01-23|13:54:35.773 [WriteBuffer-row_key_index-2] WARN  [HConnectionManager.java:302] - Could not fullfill request on this host CassandraClient<localhost:9160-87563>
01-23|13:54:35.773 [WriteBuffer-row_key_index-2] WARN  [HConnectionManager.java:303] - Exception:
me.prettyprint.hector.api.exceptions.HectorTransportException: org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe
        at me.prettyprint.cassandra.service.ExceptionsTranslatorImpl.translate(ExceptionsTranslatorImpl.java:39)
        at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:260)
        at me.prettyprint.cassandra.model.ExecutingKeyspace.doExecuteOperation(ExecutingKeyspace.java:113)
        at me.prettyprint.cassandra.model.MutatorImpl.execute(MutatorImpl.java:243)
        at org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob.run(WriteBuffer.java:358)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:785)
Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe
        at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:147)
        at org.apache.thrift.transport.TFramedTransport.flush(TFramedTransport.java:157)
        at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:65)
        at org.apache.cassandra.thrift.Cassandra$Client.send_batch_mutate(Cassandra.java:958)
        at org.apache.cassandra.thrift.Cassandra$Client.batch_mutate(Cassandra.java:949)
        at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:246)
        at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:243)
        at me.prettyprint.cassandra.service.Operation.executeAndSetResult(Operation.java:104)
        at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:253)
        ... 6 common frames omitted
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:120)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:164)
        at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145)
        ... 14 common frames omitted
01-23|13:54:35.773 [WriteBuffer-row_key_index-2] INFO  [HConnectionManager.java:404] - Client CassandraClient<localhost:9160-87563> released to inactive or dead pool. Closing.
01-23|13:54:35.773 [WriteBuffer-row_key_index-2] ERROR [WriteBuffer.java:363] - Error resending data
01-23|13:54:35.774 [Hector.me.prettyprint.cassandra.connection.CassandraHostRetryService-1] INFO  [HConnectionManager.java:109] - Added host localhost(127.0.0.1):9160 to pool

**Comment by rdzimmer** [comment]
I've taken a few javacores of the locked up KairosDB JVM.  Each javacore has the same 2 blocked threads. 
I have to kill KairosDB and restart it, but Cassandra does not need any restarts.  Again, this is with the default 500,000 buffer.  
![kairosdb_javacore_1](https://cloud.githubusercontent.com/assets/17729406/22219430/b90ececc-e178-11e6-9385-926856d9069f.PNG)

**Comment by rdzimmer** [comment]
Hmmm, looks like those 2 threads are always blocked, even in a good environment.  Something else must be locking up my KairosDB.

**Comment by rdzimmer** [comment]
I'm thinking I'm stuck in the loop ` while (m_pendingMutations != null) ` line 342 of WriteBuffer.java https://github.com/kairosdb/kairosdb/blob/9469daa937056d84de121ff112a93947e44f960e/src/main/java/org/kairosdb/datastore/cassandra/WriteBuffer.java 
For the first 2 minutes I get messages "Error sending data to Cassandra", but after that I just see "Error resending data".  I will try to learn how to build and add more error logging to that loop to find out why.  Is there a reason the exception was removed from the logging? `logger.error("Error resending data", e);`

**Comment by brianhks** [comment]
This is an excellent point and I've addressed it in the CQL branch of the code.  I'm implementing a file backed queue in Kairos so that it can buffer and smooth out these kinds of problems.

In the current code base I'm not sure I like blocking the clients and I don't really like returning errors either.

**Comment by brianhks** [comment]
I started that last comment this morning and just posted it, then I saw all your other remarks.

I think the taking out of the exception was an oversight.  I just fixed it in the develop branch.

Part of the problem may be the hector client lib.  You may try playing with some of the kairosdb.datastore.cassandra.hector.* properties to see if you can configure hector to work better.

**Comment by rdzimmer** [comment]
Thanks for the hector suggestion.  I've specifically set kairosdb.datastore.cassandra.hector.retryDownedHosts=true and I'm playing around with the other settings.  However, even with retryDownedHosts=true, once the connection to Cassandra has any issues it is lost until KairosDB is restarted.  
I added some tracing into loadMutations() to count the size of data.  Based on the size of the loadMutations counts I can see that once there is a single issue with the connection to Cassandra, the threads all get stuck retrying the same data (same size count) forever.  I'm currently looking into what could allow it to recover from a "MARK HOST AS DOWN TRIGGERED" without a restart, since Cassandra is fine after I restart KairosDB.  
Also, this sounds very similar to issue 145 https://github.com/kairosdb/kairosdb/issues/145

**Comment by rdzimmer** [comment]
I've added a lot of tracing to my WriteBuffer.java.  The WriteBuffer-X-# threads get stuck trying to run m_pendingMutations.execute() inside the while loop of run() of WriteDataJob.  
The interesting thing is that the threads do not all get stuck there at the same time.  Given the right incoming workload speed and some luck, I was able to get just one of the threads stuck in the while loop, even though all of the other threads were still going.  Eventually, all of the other threads were idle because they had completed all of their work (based on their m_buffer counts), but I still had my one WriteBuffer-data_points-1 thread stuck trying to execute its load.  After determining it was never getting out I cranked up a large workload again.  The other threads did post data for a while, but eventually became stuck too.  
I have seen that on very rare occasions, the threads can break out of the while loop.  So it is possible.  But usually, one a thread is in there it stays there, even if other threads are able to keep communicating and posting to Cassandra.  

There doesn't appear to be a magic m_buffer data size for the thread that it breaks at.  Normally (when the default is 500,000) the threads are posting between 80,000 and 100,000 each batch. 
But setting kairosdb.datastore.cassandra.write_delay=25000 does keep the threads out of the while loop completely, even when my Cassandra is just as busy.

**Comment by rdzimmer** [comment]
It looks like the issue was **thrift_framed_transport_size_in_mb** in my cassandra.yaml.  Default was 15 MB.  Once I moved to 150 MB everything has been okay (so far), even with a kairosdb.datastore.cassandra.write_delay=500000.  

I did try one thing in the KairosDB code to try to avoid this, however it did not work.  Inside the retry batch while loop, I broke up the batch into two parts by modifying loadMutations().  I figured that if the problem was that the thrift message was too big, when we retry we should try a smaller value.  It did work sometimes, but not always.  Even when the 1/2 size message should be small enough it failed.  I'll see if I just need to reduce the message even more in the retry, or if the thread/connection really is just completely broken if you exceed the Cassandra thrift_framed_transport_size_in_mb even once.  

		private int loadMutations(int start, int end) {
...
			//for (Triple<RowKeyType, ColumnKeyType, ValueType> data : m_buffer)
			for (int y = start; y < end; y++) {
				Triple<RowKeyType, ColumnKeyType, ValueType> data = m_buffer.get(y);
...
...
			while (m_pendingMutations != null) {
				try {	Thread.sleep(500);
				} catch (InterruptedException ignored) {			}
				try {
					m_pendingMutations.discardPendingMutations(); // Ensure they are empty

					int loaded = loadMutations(0, m_buffer.size()/2);
					logger.info("While loop 1 m_pendingMutations.execute() " + loaded + ", 0 to " + m_buffer.size()/2 + " of " + m_buffer.size() );
					m_pendingMutations.execute();

					loaded = loadMutations(m_buffer.size()/2, m_buffer.size());
					logger.info("While loop 2 m_pendingMutations.execute() " + loaded + ", " + m_buffer.size()/2 + " to " + m_buffer.size() );
					m_pendingMutations.execute();

					m_pendingMutations = null;
				} catch (Exception e) {
					logger.error("Error resending data", e);
				}
				escaped = true;
			}

**Comment by brianhks** [comment]
Thanks for doing all this, this is some good research.  I assume you mean kairosdb.datastore.cassandra.write_buffer_max_size not write_delay.

**Comment by rdzimmer** [comment]
Oops, I'm going back and editing out write_delay.

**Comment by rdzimmer** [comment]
I believe there are simply cases when the entire runnable `m_executorService.execute(writeDataJob)` needs to be exited and re-executed as a new spawn (broken into smaller chuncks) to prevent getting permanently stuck in the WriteDataJob retry while loop.  I'll try out some ways to do this today and see what I can find.

**Comment by rdzimmer** [comment]
I've determined that the issue was completely the thrift message size (15MB Cassandra limit).  Sometimes, breaking the message into 2 chunks was even not enough.  
In order to prevent getting stuck in the retry loop, I would recommend that the retry loop reduce the size of the message attempted each time.  In order to do this, `loadMutations` could be changed to accept a start and end value, and only return that portion of the `m_buffer` array.  

		private void loadMutations(int start, int end) {
			for (int y = start; y < end; y++) {
				Triple<RowKeyType, ColumnKeyType, ValueType> data = m_buffer.get(y);

Then, inside the retry while loop, the size of the batch could be reduced each try.  There could even be a breakout if you try too many times.

			// If the batch failed we will retry it without changing the buffer size.
			int number_of_tries = 1000; int try_number = 1;
			while (m_pendingMutations != null && try_number < number_of_tries) {
				try {Thread.sleep(500);	} catch (InterruptedException ignored) { }
				try {
					for (int x = 1; x <= try_number; x++) {
						int start = 0;
						int end = m_buffer.size();
						if (x != 1) { start = (m_buffer.size() / try_number) * (x - 1);	}
						if (x != try_number) { end = (m_buffer.size() / try_number) * x; }
						loadMutations(start, end);
						logger.info("WriteDataJob, retry loop " + x + ", adding batch " + start	+ " to " + end + " of " + m_buffer.size() + ", try " + try_number);
						m_pendingMutations.execute();
					}
					m_pendingMutations = null;
				} catch (Exception e) {	logger.error("Error resending data", e); }
				try_number++;
			}
			if (m_pendingMutations != null) { logger.error("WriteDataJob, could not send data after trying " + try_number + " times, size " + m_buffer.size());	}
