### ISSUE TITLE
Incorrect FileQueue deserializeEvent exception handling

### ISSUE THREAD

**Issue by xelex** [kairosdb/kairosdb#477]
Kairos: 1.2.1
Cassandra: latest, from docker
Config: default + FileQueueProcessor

KairosDB can not read queue data from the disk after restart.
And it lasts "forever".

`06-13|12:48:41.307 [main] INFO  [Main.java:405] - ------------------------------------------
06-13|12:48:41.307 [main] INFO  [Main.java:406] -      KairosDB service started
06-13|12:48:41.307 [main] INFO  [Main.java:407] - ------------------------------------------
06-13|12:49:31.700 [QueueProcessor-0] ERROR [QueueProcessor.java:192] - DeliveryThread Exception
java.lang.IllegalStateException: java.io.EOFException
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:383)
        at org.kairosdb.core.queue.DataPointEventSerializer.deserializeEvent(DataPointEventSerializer.java:65)
        at org.kairosdb.core.queue.FileQueueProcessor.get(FileQueueProcessor.java:192)
        at org.kairosdb.core.queue.QueueProcessor$DeliveryThread.run(QueueProcessor.java:173)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: null
        at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
        at java.io.DataInputStream.readUTF(DataInputStream.java:589)
        at java.io.DataInputStream.readUTF(DataInputStream.java:564)
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:381)
        ... 6 common frames omitted`

**Comment by derula** [comment]
@brianhks hm, milestone 1.2.2, but not fixed in 1.2.2... is this still in the pipeline? I believe that when this bug occurs, KairosDB is stuck at 100% CPU usage, which isn't very good. For me, it seems to "randomly" occur every now and then, and there is no obvious way to stop it other then shutting down KairosDB.

Is there a workaround I could use until this is fixed? Sadly I don't know any Java, or I'd try to fix it myself.

**Comment by jsgamboaq** [comment]
I think i´ve found a workaround for this bug: Deleting meta_data/page-0.dat file on the queue folder and restarting the service did the work for me.

**Comment by brianhks** [comment]
Error handling was added in 1.3.0 to deal with this.  Yes the work around is viable.  The file backed queue gets bad data in it.

**Comment by jsgamboaq** [comment]
Is there a way to recover from this error without losing data on queue? We are currently seeing this error randomly, deleting meta_data/page-0.dat and restarting works, but all the data that was sent to KairosDB during the period the exceptions starts showing is not inserted to Cassandra, seems like data remains in file backed queue, but without the correct metadata is ignored.

**Comment by brianhks** [comment]
Probably the only way is to use a hex editor to edit the dat files.  You would have to look at the format as it is written by bigqueue and then figure out what to change.
