### ISSUE TITLE
NPE on startup when modifying rollup scheduling

### ISSUE THREAD

**Issue by atulkc** [kairosdb/kairosdb#511]
We are running kairos to save and rollup metrics. On restart of kairos nodes we see following exception trace in the log. Kairos is used with Casandra as backing datastore. 

```
17:16:16.740 [Roll-up-Modification-Checker-0] ERROR [SchedulingManager.java:137] - Failed to modify roll-up scheduling
java.lang.NullPointerException: null
	at org.kairosdb.rollup.RollUpAssignmentStoreImpl.getAssignments(RollUpAssignmentStoreImpl.java:74)
	at org.kairosdb.rollup.SchedulingManager.checkSchedulingChanges(SchedulingManager.java:112)
	at org.kairosdb.rollup.SchedulingManager$CheckChanges.run(SchedulingManager.java:97)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jsabin** [comment]
The rollup has been assigned for a server to process but the value of that assignment is missing. This should not be possible. I added a logging statement to detect this case and remove it from the table so it will be reassigned. While this does not fix the actual problem, the rollup will get assigned and processed. See commit #eccaa35a0b0e1159567e343270e09b322bc1da7c.
