### ISSUE TITLE
ERROR [MetricsResource.java:396] - Failed to add metric.

### ISSUE THREAD

**Issue by mr-yaky** [kairosdb/kairosdb#561]
Hi, I use KairosDB `1.2.2` version with Cassandra `3.11.3`  as persistent backend.
Also this stack installed on Kubernetes:
1 replica for KairosDB
3 replicas for Cassandra

KairosDB Cassandra main options:
```
kairosdb.datastore.cassandra.cql_host_list: cassandra
kairosdb.datastore.cassandra.read_consistency_level=ONE
kairosdb.datastore.cassandra.write_consistency_level=QUORUM
kairosdb.datastore.cassandra.replication={'class': 'SimpleStrategy','replication_factor' : 3}
```

```
# cqlsh
Connected to cassandra at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.11.3 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cqlsh> describe keyspace kairosdb

CREATE KEYSPACE kairosdb WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;
```

We get this error from time to time randomly and we receive some `null` values when try to fetch the data from KairosDB:

```
03:00:33.445 [Ingest worker-532] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/index/page-5.dat was just deleted.
03:21:51.976 [Ingest worker-565] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-20.dat was just deleted.
03:31:04.685 [qtp508760925-387990] ERROR [MetricsResource.java:396] - Failed to add metric.
java.lang.NullPointerException: null
	at org.kairosdb.core.http.rest.json.DataPointsParser$NewMetric.access$000(DataPointsParser.java:398)
	at org.kairosdb.core.http.rest.json.DataPointsParser.validateAndAddDataPoints(DataPointsParser.java:259)
	at org.kairosdb.core.http.rest.json.DataPointsParser.parse(DataPointsParser.java:94)
	at org.kairosdb.core.http.rest.MetricsResource.add(MetricsResource.java:372)
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.kairosdb.core.http.MonitorFilter.doFilter(MonitorFilter.java:81)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.kairosdb.core.http.LoggingFilter.doFilter(LoggingFilter.java:48)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:82)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:294)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
03:52:19.805 [Ingest worker-591] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-21.dat was just deleted.
04:21:15.749 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-22.dat was just deleted.
```

Can anyone give some recommendations to fix it or what we missed in our configuration?

**Comment by brianhks** [comment]
This looks to me like someone is sending bad json to kairos and we are not catching it properly.  I'm trying to look through the code to see how that could happen.  If you find it post what the json looks like so we can tighten up our error checking.

**Comment by BrentonPoke** [comment]
@brianhks Would it help to validate that the json string is valid in the query parser? This is my guess based on what the QueryParser object already does. It looks like there's a query object validator (that I haven't yet looked into yet) but no current checking to see if the json is valid to begin with.

**Comment by brianhks** [comment]
The error in the original post is from posting data not querying it.

**Comment by BrentonPoke** [comment]
So the object plays no role in posting the data?

**Comment by brianhks** [comment]
In the original post the error is coming from DataPointsParser which is used to parse incoming data not queries.  As the line right above the error states "Failed to add metric."

In order to investigate this further I would need the json that is sent to the server to make sure the errors are appropriate and informative.

**Comment by brianhks** [comment]
Please reopen if you can provide the failed json
