### ISSUE TITLE
Azure CosmosDB Connection Error

### ISSUE THREAD

**Issue by biswaKL** [kairosdb/kairosdb#580]
Hi, i took the code, disabled LZ4, and after that i am trying to connect to Azure CosmosDB (cassandra API) , connection is not happening which is a separate issue. But i am also seeing this in log:

`00:52:14.294 [cluster1-worker-0] INFO  [SchemaParser.java:113] - Asked to rebuild TABLE kairosdb.data_points but I don't know keyspace kairosdb
00:52:15.642 [cluster1-worker-0] INFO  [SchemaParser.java:113] - Asked to rebuild TABLE kairosdb.string_index but I don't know keyspace kairosdb
00:52:17.126 [cluster1-worker-0] INFO  [SchemaParser.java:113] - Asked to rebuild TABLE kairosdb.tag_indexed_row_keys but I don't know keyspace kairosdb
00:52:18.992 [main] ERROR [CassandraModule.java:180] - Error building write cluster
com.datastax.driver.core.exceptions.InvalidQueryException: DELETE statements must restrict all PRIMARY KEY columns with equality relations in order to delete non static columns
        at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:49)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
        at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:86)
        at org.kairosdb.datastore.cassandra.ClusterConnection.tryToConnect(ClusterConnection.java:401)
        at org.kairosdb.datastore.cassandra.ClusterConnection.startup(ClusterConnection.java:383)
        at org.kairosdb.datastore.cassandra.CassandraModule.createClients(CassandraModule.java:149)
        at org.kairosdb.datastore.cassandra.CassandraModule.getWriteCluster(CassandraModule.java:175)
        at org.kairosdb.datastore.cassandra.CassandraModule$$FastClassByGuice$$80c3d494.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
        at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
        at org.kairosdb.core.scheduler.KairosDBSchedulerImpl.start(KairosDBSchedulerImpl.java:69)
        at org.kairosdb.core.Main.startServices(Main.java:568)
        at org.kairosdb.core.Main.main(Main.java:414)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: DELETE statements must restrict all PRIMARY KEY columns with equality relations in order to delete non static columns
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:181)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:251)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
        at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
        at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by biswaKL** [comment]
I have found out that these queries are throwing error in CosmosDB, 
`02:25:44.402 [main] INFO  [ClusterConnection.java:401] - Executing query: DELETE FROM kairosdb.data_points WHERE key = ?`
`02:25:44.403 [main] INFO  [ClusterConnection.java:405] - Executing query: DELETE FROM kairosdb.data_points WHERE key = ? AND column1 >= ? AND column1 <= ?`


Mostly all the delete queries are giving error.

**Comment by brianhks** [comment]
So when kairos starts up it always tries to create the schema, in ClusterConnection setupSchema is always called after connecting.  I think that is what is generating your first error you posted.  As for the delete calls they may not support all of the functionality of Cassandra.  I would think they would give an error when kairos tries to prepare the statement.
