### ISSUE TITLE
Unable to Export data from Kairos (H2)

### ISSUE THREAD

**Issue by biswaKL** [kairosdb/kairosdb#597]
I am trying to export the data from KairosDB in H2 Datastore using the following command: `bin/kairosdb.sh export | gzip > export.gz`

but getting the error:

```bash
Exception in thread "main" org.agileclick.genorm.runtime.GenOrmException: java.sql.SQLException: Connections could not be acquired from the underlying database!
        at org.kairosdb.datastore.h2.orm.MetricNamesQuery.runQuery(MetricNamesQuery.java:130)
        at org.kairosdb.datastore.h2.H2Datastore.getMetricNames(H2Datastore.java:240)
        at org.kairosdb.core.datastore.KairosDatastore.getMetricNames(KairosDatastore.java:215)
        at org.kairosdb.core.Main.runExport(Main.java:473)
        at org.kairosdb.core.Main.main(Main.java:349)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
        at org.agileclick.genorm.runtime.GenOrmDudConnection.prepareStatement(GenOrmDudConnection.java:110)
        at org.kairosdb.datastore.h2.orm.GenOrmDataSource.prepareStatement(GenOrmDataSource.java:302)
        at org.kairosdb.datastore.h2.orm.MetricNamesQuery.runQuery(MetricNamesQuery.java:102)
        ... 4 more
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
        ... 8 more
```

**Comment by brianhks** [comment]
This looks to be working in 1.3, what version are you using?
