### ISSUE TITLE
Error in cassandra

### ISSUE THREAD

**Issue by biswaKL** [kairosdb/kairosdb#599]
While starting the KairosDB i am getting the below error:

```
06:43:28.147 [main] ERROR [CassandraModule.java:136] - Unable to setup cassandra schema
com.datastax.driver.core.exceptions.SyntaxError: COMPACT STORAGE tables are not allowed starting with version 4.0
        at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
        at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:43)
        at org.kairosdb.datastore.cassandra.Schema.setupSchema(Schema.java:301)
        at org.kairosdb.datastore.cassandra.Schema.<init>(Schema.java:225)

```

**Comment by kyleboyle** [comment]
The non-breaking way to fix this is to only create tables with compact storage for c* 2.x, and no use it for it for later versions since it has no effect on C 3+.

Is it possible to get cassandra cluster version via the java driver?

**Comment by brianhks** [comment]
Correct the compact storage was moved into configuration that you can override/remove in 1.3 beta.  Older versions were hard coded.
