### ISSUE TITLE
auto start cassandra  and kairosdb 

### ISSUE THREAD

**Issue by nimrodnan** [kairosdb/kairosdb#623]
When  auto start, it immediately executes kairosdb start after executing cassandrd. the following error will be reported.
But it's OK when executes cassandra  for a while, and then executes kairosdb.

 Shutdown exception:
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.IllegalStateException: Can't use this cluster instance because it was previously closed
  at org.kairosdb.datastore.cassandra.CassandraModule.getCassandraSchema(CassandraModule.java:132)
  at org.kairosdb.datastore.cassandra.CassandraModule.getCassandraSchema(CassandraModule.java:132)
  while locating org.kairosdb.datastore.cassandra.Schema
    for the 3rd parameter of org.kairosdb.datastore.cassandra.CassandraDatastore.<init>(CassandraDatastore.java:159)
  at org.kairosdb.datastore.cassandra.CassandraModule.configure(CassandraModule.java:80)
  while locating org.kairosdb.datastore.cassandra.CassandraDatastore
  at org.kairosdb.datastore.cassandra.CassandraModule.configure(CassandraModule.java:78)
  while locating org.kairosdb.core.datastore.Datastore
    for the 1st parameter of org.kairosdb.core.datastore.KairosDatastore.<init>(KairosDatastore.java:81)
  at org.kairosdb.core.CoreModule.configure(CoreModule.java:159)
  while locating org.kairosdb.core.datastore.KairosDatastore
Caused by: java.lang.IllegalStateException: Can't use this cluster instance because it was previously closed
        at com.datastax.driver.core.Cluster.checkNotClosed(Cluster.java:604)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:329)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)
        at com.datastax.driver.core.Cluster.connect(Cluster.java:247)
        at org.kairosdb.datastore.cassandra.CassandraClientImpl.getSession(CassandraClientImpl.java:139)
        at org.kairosdb.datastore.cassandra.Schema.setupSchema(Schema.java:293)
        at org.kairosdb.datastore.cassandra.Schema.<init>(Schema.java:225)
        at org.kairosdb.datastore.cassandra.CassandraModule.getCassandraSchema(CassandraModule.java:132)
        at org.kairosdb.datastore.cassandra.CassandraModule$$FastClassByGuice$$80c3d494.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)

**Comment by brianhks** [comment]
someone just needs to get off their arse and finish the 1.3 release.  There is a feature there that lets you start kairos async - meaning it continues to retry connecting to cassandra in order to prevent the race condition you describe.
