### ISSUE TITLE
Error with kairosdb.service.carbon=org.kairosdb.core.carbon.CarbonServerModule

### ISSUE THREAD

**Issue by ghost** [kairosdb/kairosdb#80]
Please help me
03:13:17.205 [main] ERROR [Main.java:154] - Unable to load service kairosdb.service.carbon
java.lang.ClassNotFoundException: org.kairosdb.core.carbon.CarbonServerModule
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_55]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_55]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_55]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_55]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_55]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_55]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_55]
        at java.lang.Class.forName0(Native Method) ~[na:1.7.0_55]
        at java.lang.Class.forName(Class.java:190) ~[na:1.7.0_55]
        at org.kairosdb.core.Main.<init>(Main.java:126) [kairosdb-0.9.4-6.jar:0.9.4-6.20140730155336]
        at org.kairosdb.core.Main.main(Main.java:205) [kairosdb-0.9.4-6.jar:0.9.4-6.20140730155336]

**Comment by KlavsKlavsen** [comment]
appearently that plugins.html  does not exist anymore - and https://kairosdb.github.io/docs/build/html/Graphite.html still shows what appearently is the WRONG (and not working) way of enabling Carbon support in kairosdb :(

**Comment by KlavsKlavsen** [comment]
to those finding this issue - you can find the plugin here: https://github.com/kairosdb/kairos-carbon - including install instructions.
